spring:
  datasource:
    url: jdbc:mysql://localhost:3306/esercizio_hal_2
    username: root
    password:
  jpa:
    database: mysql
    show_sql: true
    hibernate:
      ddl-auto: create
  jackson:
    serialization:
      fail-on-empty-beans: false

server:
  port: 5050